//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETUT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EtutEntities1 : DbContext
    {
        public EtutEntities1()
            : base("name=EtutEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
        public virtual DbSet<TBLOGRBRANS> TBLOGRBRANS { get; set; }
        public virtual DbSet<TBLOGRENCI> TBLOGRENCI { get; set; }
        public virtual DbSet<TBLOGRETMEN> TBLOGRETMEN { get; set; }
        public virtual DbSet<TBLOGRSINIF> TBLOGRSINIF { get; set; }
        public virtual DbSet<TBLORTALAN> TBLORTALAN { get; set; }
        public virtual DbSet<TBLETUT> TBLETUT { get; set; }
        public virtual DbSet<TBLSAAT> TBLSAAT { get; set; }
    }
}
