//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETUT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADMIN
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string TC { get; set; }
        public string TELNO { get; set; }
        public string SIFRE { get; set; }
        public string EPOSTA { get; set; }
    }
}
