//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETUT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLETUT
    {
        public int ID { get; set; }
        public Nullable<int> OGRETMENID { get; set; }
        public Nullable<int> OGRENCIID { get; set; }
        public Nullable<int> ALANID { get; set; }
        public List<SaatTarihViewModel> Liste { get; set; } // Liste özelliði
        public System.DateTime ZAMAN { get; set; }
        public bool AKTIFMI { get; set; }
        public Nullable<int> SAATID { get; set; }    
        public virtual TBLOGRENCI TBLOGRENCI { get; set; }
        public virtual TBLOGRETMEN TBLOGRETMEN { get; set; }
        public virtual TBLORTALAN TBLORTALAN { get; set; }
        public virtual TBLSAAT TBLSAAT { get; set; }
    }
}
