//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETUT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOGRSINIF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLOGRSINIF()
        {
            this.TBLOGRENCI = new HashSet<TBLOGRENCI>();
        }
    
        public int ID { get; set; }
        public string SINIFSEVIYESI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLOGRENCI> TBLOGRENCI { get; set; }
    }
}
