//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETUT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text.RegularExpressions;

    public partial class TBLOGRETMEN
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLOGRETMEN()
        {
            this.TBLETUT = new HashSet<TBLETUT>();
            KAYITDURUMU = false;

        }

        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }

        [RegularExpression(@"^[1-9]{1}[0-9]{9}[02468]{1}$", ErrorMessage = "Geçersiz TC kimlik numarasý")]
        public string TC { get; set; }

        [RegularExpression(@"^((05|5)(\d{9}))$", ErrorMessage = "Geçersiz telefon numarasý")]
        public string TELNO { get; set; }
   
        [StringLength(20, MinimumLength = 8, ErrorMessage = "Þifre 8-20 karakter arasýnda olmalýdýr")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$", ErrorMessage = "Þifre güçlü deðildir. Þifrenin en az bir küçük harf, en az bir büyük harf, en az bir rakam, en az bir özel karakter ve en az 8 karakter olmasý gerekmektedir.")]
        public string SIFRE { get; set; }
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@(msn|hotmail|gmail)\.com$", ErrorMessage = "Geçersiz e-posta adresi")]
        public string EPOSTA { get; set; }
        public Nullable<int> ALANID { get; set; }
        public Nullable<bool> KAYITDURUMU { get; set; }
    
        public virtual TBLORTALAN TBLORTALAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLETUT> TBLETUT { get; set; }
    }
}
